from __future__ import annotations

import os
from datetime import timedelta, timezone

API_INTERNAL = os.getenv("API_BASE_URL", "http://nginx/api")
AUTH_COOKIE_NAME = "semantic_news_novelty_access_token"
AUTH_COOKIE_TTL_DAYS = int(os.getenv("AUTH_COOKIE_TTL_DAYS", "1"))
MOSCOW_TIMEZONE = timezone(timedelta(hours=3))

PAGE_LABELS = {
    "Search": "Поиск",
    "News": "Мои новости",
    "Transactions": "Операции",
    "Admin": "Администрирование",
}
ROLE_LABELS = {
    "user": "Пользователь",
    "publisher": "Редактор",
    "admin": "Администратор",
}

NEWS_TABLE_WIDTH = 1520
SELECT_COLUMN_WIDTH = 44
DATE_COLUMN_WIDTH = 190
SOURCE_COLUMN_WIDTH = 120

DRAFT_REVIEW_COLUMN_WIDTH = 250
DRAFT_TITLE_COLUMN_WIDTH = (
    NEWS_TABLE_WIDTH
    - SELECT_COLUMN_WIDTH
    - DATE_COLUMN_WIDTH
    - DRAFT_REVIEW_COLUMN_WIDTH
    - SOURCE_COLUMN_WIDTH
)

ARCHIVE_TYPE_COLUMN_WIDTH = 160
ARCHIVE_TITLE_COLUMN_WIDTH = (
    NEWS_TABLE_WIDTH
    - SELECT_COLUMN_WIDTH
    - DATE_COLUMN_WIDTH
    - ARCHIVE_TYPE_COLUMN_WIDTH
    - SOURCE_COLUMN_WIDTH
)

PUBLISHED_STATUS_COLUMN_WIDTH = 135
PUBLISHED_MODEL_TYPE_COLUMN_WIDTH = 160
PUBLISHED_EDITOR_LABEL_COLUMN_WIDTH = 200
PUBLISHED_EFFECTIVE_TYPE_COLUMN_WIDTH = 190
PUBLISHED_IMPORTANCE_COLUMN_WIDTH = 120
PUBLISHED_TITLE_COLUMN_WIDTH = (
    NEWS_TABLE_WIDTH
    - SELECT_COLUMN_WIDTH
    - DATE_COLUMN_WIDTH
    - PUBLISHED_STATUS_COLUMN_WIDTH
    - PUBLISHED_MODEL_TYPE_COLUMN_WIDTH
    - PUBLISHED_EDITOR_LABEL_COLUMN_WIDTH
    - PUBLISHED_EFFECTIVE_TYPE_COLUMN_WIDTH
    - PUBLISHED_IMPORTANCE_COLUMN_WIDTH
    - SOURCE_COLUMN_WIDTH
)
